POST http://localhost:11434/api/chat  HTTP/1.1
content-type: application/json

{
  "model": "llama3.2",
  "stream": true,
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}